#+TITLE: Ejercicios del Tema 4, cadenas
#+SUBTITLE: Cadenas de caracteres
#+AUTHOR: 
#+DATE: 
#+SETUPFILE: config.org
#+PROPERTY: header-args :exports none
#+EXPORT_FILE_NAME: ejercicios_tema4_cadenas.pdf


* 1. Espacios por guiones

Escribe  un programa que cambie los espacios en blanco por un guión bajo =_= en la frase siguiente:

#+begin_src C  :exports code
char texto[] = "Vamos a practicar programacion mas a menudo.";
#+end_src

#+BEGIN_SRC C 
#include <stdio.h>

int main()
{
  //Asignamos el texto a una variable char, sin definir la dimension
  char texto[] = "Vamos a practicar programacion mas a menudo.";

  int i = 0;
  //Recorremos el texto hasta el final
  while(texto[i] != '\0')
  {
    if(texto[i] == ' ') //Si encuentra un espacio
    {
      texto[i] = '_'; //lo sustituye por un guion bajo
    }
    i++;
  }
  printf("%s\n", texto); //Imprime el resultado

  return 0;    
}
#+END_SRC


* 2. Letras al revés

Escribe un programa que imprima al revés una palabra o frase introducida por teclado. (ejemplo: casa roja se convierte en (ajor asac).

#+BEGIN_SRC C 
#include <stdio.h>

int main ()
{
  char palabra[15];
  int len, i;
  // Pide la palabra al usuario
  printf("Escribe una palabra o frase (máximo 14 letras):\n");
  scanf("%11[^\n]", palabra);
  
  // Calcula la longitud de la cadena
  i = 0;
  while (palabra[i] != '\0')
  {
    i++;
  }
  len = i;
  
  // Empezamos por el último caracter (len - 1) y retrocedemos hasta
  // el primero (0)
  for(i = len-1; i >= 0; i--)
  {
    printf("%c", palabra[i]);
  }
    
  return 0;
}
#+END_SRC


* 3. Separa palabras

Escribe un programa que pida al usuario introducir una frase.
Después. imprima cada palabra en una nueva línea.

#+BEGIN_SRC C 
#include <stdio.h>

int main() 
{
    char frase[200];
    int i = 0;

    // Pedir la frase al usuario
    printf("Ingrese una frase: ");
    gets(frase);

    // Recorrer la cadena e imprimir palabra por palabra
    while (frase[i] != '\0') 
    {
        if ( (frase[i] == ' ') || (frase[i] == ',') || (frase[i] == '.') )
        {
            printf("\n"); // Salto de línea al encontrar un espacio
        } else 
        {
            printf("%c", frase[i]);
        }
        i++;
    }

    return 0;
}
#+END_SRC


* 4. Pedir frase

#+BEGIN_SRC C 
#include <stdio.h>

int main() 
{
    char frase[50];
    int tieneEspacio = 0;

    do 
    {
        tieneEspacio = 0; // Reiniciamos la bandera
        
        // Pedir la frase al usuario
        printf("Ingrese una frase con varias palabras: ");
	gets(frase);
				
	int i = 0;
        // Verificar, hasta el final de la cadena, si hay algún un espacio
        while ( frase[i] != '\0') 
        {
            if (frase[i] == ' ') 
            {
                tieneEspacio = 1;
            }
            i++;
        }

        // Si no hay espacios, pedir otra frase
        if (tieneEspacio == 0) 
				{
            printf("Debe ingresar mas de una palabra. Intentelo nuevamente.\n");
        }

    } while (!tieneEspacio); // Se repite mientras no haya espacios

    printf("Frase aceptada: %s", frase);

    return 0;
}
#+END_SRC


* 5. Convertir letras

Escribe un programa que después de introducir una palabra convierta una de cada 2 letras, de mayúsculas a minúsculas, o viceversa. Siga pidiendo palabras hasta que se introduzca el caractrer 0 para terminar el programa. 

#+BEGIN_SRC C 
#include <stdio.h>

int main() 
{
  char palabra[25]; // Vector para almacenar la palabra ingresada.
  int i;

  printf("Introduce una palabra (o 0 para terminar): ");
  // Leer una palabra hasta 4 letras
  scanf("%24s", palabra);
      
  while (palabra[0] != '0') 
  {
    // Convertir y alternar mayúsculas/minúsculas para cada letra.
    i = 0;
    while ( palabra[i] != '\0' ) 
    {
      // Cambiamos solo los caracteres en posiciones pares
      if (i % 2 == 0) 
      {
        // Convertir a mayúscula si es minúscula.
        if (palabra[i] >= 'a' && palabra[i] <= 'z') 
        {
          palabra[i] = palabra[i] - ('a' - 'A');
        }
        // Convertir a minúscula si es mayúscula.
        else 
        {
          if (palabra[i] >= 'A' && palabra[i] <= 'Z') 
          {
            palabra[i] = palabra[i] + ('a' - 'A');
          }
        }
      }
      i++;
    }

    printf("Resultado: %s\n\n", palabra);
    
    printf("Introduce una palabra (o 0 para terminar): ");
    // Leer una palabra hasta 4 letras
    scanf("%24s", palabra);
  }

  printf("Programa terminado.\n");
  return 0;
}
#+END_SRC


* 6. Cuenta letras

Escribe un programa que analice una frase contando en número de veces que aparece cada vocal. Al final del programa, se debe pintar en el terminal, para cada letra, una línea que contiene el mismo número de asteríscos que veces aparece esa vocal.

#+BEGIN_SRC C 
#include <stdio.h>

int main()
{
  char frase[] = "Vamos a practicar programacion mas a menudo.";
  
  char vocales[5] = {'a', 'e', 'i', 'o', 'u'};
  int i, j; 
  int nLetra[5] = {0, 0, 0, 0, 0};  //Vector de resultados

  // Cuenta las apariciones de cada vocal, y almacena resultados en nLetra
  i = 0;
  while (frase[i] != '\0') // Recorre la cadena de caracteres
  {
    switch(frase[i]) // Compara el caracter con las vocales
    {
      case 'a':
      case 'A':
        nLetra[0]++;
      break;
    
      case 'e':
      case 'E':
        nLetra[1]++;
      break;
    
      case 'i':
      case 'I':
        nLetra[2]++;
      break;
  
      case 'o':
      case 'O':
        nLetra[3]++;
      break;
  
      case 'u':
      case 'U':
        nLetra[4]++;
      break;
    }
  // Avanzo en la frase  
  i++; 
  }
  // Recorre el vector de resultados, y pinta asteriscos
  // correspondientes a cada letra
  for (i = 0; i < 5; i++)
  { 
    printf("%c: ", vocales[i]);
    for (j = 1; j <= nLetra[i]; j++)
    {
      printf("*");
    }
    printf("\n");
  }
  
  return 0;
}
#+end_src

#+END_SRC


* 7. Sustituir string.h

Realice sus propios programas para suplir a las funciones: strlen(), strcpy(), strcat(), strcmp().

  * a. strlen()
#+BEGIN_SRC C 
#include <stdio.h>
#include <string.h>

int main()
{
  char cadena[] = "nombre.apellidos@upm.es";

  int contador = 0;
  while (cadena[contador] != '\0') 
  {
    contador++;
  }
  
  printf("El tamanho de la cadena es %i caracteres\n", contador);
  printf("El tamanho de la cadena es %i caracteres", strlen(cadena));

  return 0;
}
#+END_SRC

  * b. strcpy()
#+BEGIN_SRC C 
#include <stdio.h>
#include <string.h>

int main()
{
  char cadena[] = "david";
  char copia1[10];
  char copia2[10];

  int contador = 0;
  // Se copian todos los caracteres
  while (cadena[contador] != '\0') 
  {
    copia1[contador] = cadena[contador];
    contador++;
  }
  // Al final se anhade el caracter terminador de la cadena
  copia1[contador+1] = '\0';
  printf("Esta es la cadena copiada manualmente: %s \n", copia1);
  strcpy(copia2, cadena);
  printf("Esta es la cadena copiada con strcpy: %s \n", copia2);

  return 0;
}
#+END_SRC

  * c. strcat()
#+BEGIN_SRC C 
#include <stdio.h>
#include <string.h>

int main()
{
  char cadena1[] = "david";
  char cadena2[] = " alvarez";
  char cadenas_juntas[20];

  int contador1 = 0;
  // Se copian todos los caracteres de la primera cadena
  while (cadena1[contador1] != '\0') 
  {
    cadenas_juntas[contador1] = cadena1[contador1];
    contador1++;
  }
  int contador2 = 0;
  while (cadena2[contador2] != '\0') 
  {
    cadenas_juntas[contador1] = cadena2[contador2];
    contador1++;
    contador2++;
  }  
  // Al final se anhade el caracter terminador de la cadena
  cadenas_juntas[contador1+1] = '\0';
  printf("Esta es la cadena junta: %s \n", cadenas_juntas);
  printf("Esta es la cadena junta: %s \n", strcat(cadena1, cadena2));

  return 0;
}
#+END_SRC

  * d. strcmp()
#+BEGIN_SRC C 
#include <stdio.h>
#include <string.h>

int main()
{
  char cadena1[] = "david";
  char cadena2[] = "david";

  int contador = 0;
  while ((cadena1[contador] == cadena2[contador]) && (cadena1[contador] != '\0')) 
  {
    contador++;
  }
  int result;
  if( cadena1[contador] == '\0')
  {
    result = 0;
  }
  else
  {
    if( (cadena1[contador] - cadena2[contador]) < 0)
    {
      result = -1;
    }
    else
    {
      result = 1;
    }
  }
  printf("Resultado comparacion: %i \n", result);
  printf("Resultado comparacion: %i \n", strcmp(cadena1, cadena2));

  return 0;
}
#+END_SRC


* 8. Encriptar texto

En este ejercicio debes realizar un programa que encripte una cadena de caracteres empleando un número entero como clave de encriptación. En este programa el contenido de la cadena será tu correo electrónico de la UPM, y la clave se determinará a partir de tu número de matrícula. Escribe la cadena en el propio código).
Debes calcular la suma de las cifras de tu número de matrícula. Si tu número de matrícula es impar, el programa debe asignar un signo negativo al resultado. Por ejemplo, si tu número de matrícula es 12345 el resultado de este paso debe ser -15, y si es 43210 el resultado es 10. Éste valor será la clave de encriptación.
Además, define una cadena de caracteres y asígnale tu correo electrónico de la UPM, crea otra cadena para encriptar el correo. El programa recorre la cadena de caracteres sumando a cada carácter la clave de encriptación (con su signo) salvo a los puntos y a la @, que serán copiados sin cambios.
Para finalizar, el programa debe mostrar en pantalla el correo original y el correo encriptado.

#+BEGIN_SRC C 
#include <stdio.h>
int main()
{
  char correo[] = "nombre.apellidos@upm.es", encriptado[] = "nombre.apellidos@upm.es";
  int matricula = 12345, x, y, suma = 0, i;
  x = matricula;
  while(x > 0)
  {
    y = x % 10;
    suma += y;
    x /= 10;
  }
  if (matricula % 2 != 0)
    suma = - suma;
  i = 0;
  while (correo[i] != '\0')
  {
    if( (correo[i] != '.') && (correo[i] != '@') )
    {
      encriptado[i] = correo[i] + suma;
    }
    else
    {
      encriptado[i] = correo[i];
    }
    i++;
  }
  encripta[i] = '\0';
  printf("El correo original es %s y el encriptado es %s.\n", correo, encriptado);

  return 0;
}
#+END_SRC


* 9. Mover letras en palabra

Introduzca una palabra por teclado de 4 letras. Realice un programa que permita llevar la última letra al inicio y muestre por pantalla el resultado. Repítalo hasta recomponer nuevamente la palabra ingresada. (ejemplo: casa -> acas -> saca -> asac -> casa).

#+BEGIN_SRC C 
#include <stdio.h>

#define TAM 5

int main() 
{
    char palabra[TAM], temp;
    int i, ciclos = 1;

    printf("Introduzca una palabra: ");
    scanf("%4s", palabra);
  
    do 
    {
        // Mover la última letra al inicio
        // Primero se hace una copia de la última letra para no perderla
        temp = palabra[TAM - 2];
        // Se mueven el resto de letras una posición
        for (i = TAM - 2; i > 0; i--) 
        {
            palabra[i] = palabra[i - 1];
        }
        // Y se copia la letra guardada al principio en su posición
        palabra[0] = temp;

        // Incrementar el contador de ciclos
        ciclos++;
        printf("Ciclo %i: %s\n", ciclos, palabra);

    // Continuar hasta que la palabra modificada sea igual a la original
    } while (ciclos < TAM);

    printf("La palabra '%s' fue recompuesta después de %i ciclos.\n", palabra, ciclos);

    return 0;
}
#+END_SRC


* 10.  Gira palabras

Escribe un programa que procese la frase del ejercicio 1. Como resultado, cada palabra de la frase
debe de escribrila al revés.

#+BEGIN_SRC C
#include <stdio.h>

int main() 
{
    char frase[100];
    int i, inicio = 0, fin, temp, longitud = 0;

    // Leer la frase del usuario
    printf("Ingrese una frase: ");
    scanf(" %[^\n]", frase); // Lee la línea completa

    // Calcular la longitud de la frase
    while (frase[longitud] != '\0') 
    {
        longitud++;
    }

    // Recorrer la frase y encontrar palabras
    for (i = 0; i <= longitud; i++) 
    {
        if (frase[i] == ' ' || frase[i] == '\0') 
        {
            fin = i - 1;
            // Invertir la palabra encontrada
            while (inicio < fin) 
            {
                temp = frase[inicio];
                frase[inicio] = frase[fin];
                frase[fin] = temp;
                inicio++;
                fin--;
            }
            inicio = i + 1;
        }
    }

    // Imprimir la frase con palabras invertidas
    printf("Frase con palabras invertidas: %s\n", frase);

    return 0;
}
#+END_SRC


* 11. Buscar nombre

Construya un programa que almacene en un vector los nombres de un grupo de 4 personas. Separe los nombres del vector con comas. A continuación, pida un nombre y busque la posición (primer nombre, segundo nombre...) del vector en la que se almacena el mismo nombre, imprima la posición. Si dicho nombre no está en el vector, el programa deberá informarlo.

#+BEGIN_SRC C 
#include <stdio.h>

#define MAX_NOMBRE 10

int main() 
{
  char nombres[] = "david,maria,jorge,manuela";
  int i,j, posicion, encontrado;
  char nombreBuscado[MAX_NOMBRE];

  // Pedir al usuario el nombre a buscar
  printf("Ingrese el nombre de la persona a buscar: ");
  scanf("%19s", nombreBuscado);
    
  // Buscar el nombre en la cadena
  encontrado = 0;
  posicion = 0; // Posición inicial del nombre en la lista
  i = 0;
  while (nombres[i] != '\0') 
  {
    posicion++;
    // usamos i para comprobar el vector de nombres
    // usamos j para comprobar el nombre
    // si el nombre es el último, encontraríamos el caracter \0
    j = 0;
    while( (nombreBuscado[j] == nombres[i]) && (nombreBuscado[j] != '\0')) 
    {
      j++;
      i++;
    }
    // Al acabar, comprobamos por qué hemos salido del bucle
    // Si hemos llegado al final del nombre, es que lo hemos encontrado
    if (nombreBuscado[j] == '\0') 
    {
      encontrado = 1;
      printf("El nombre '%s' se encontro en la posicion %i de la lista.\n", nombreBuscado, posicion);
      i++;
    }
    // cualquier otra razón, los nombres no son iguales
    else
    {
      // avanzamos hasta la sigueinte coma o el final del vector
      while( (nombres[i] != ',') && (nombres[i] != '\0') ) 
      {
        i++;
      }
      // si llegamos a una coma, avazamos uno más para dejar atrás la coma
      if(nombres[i] == ',')
      {
        i++;  
      }
    }
  }

  if (encontrado == 0) 
  {
    printf("El nombre '%s' no se encontró en la lista.\n", nombreBuscado);
  }

  return 0;
}
#+END_SRC

  * Otra solución
#+BEGIN_SRC C
#include <stdio.h>

// Construya un programa que almacene en un vector los nombres de un grupo de n personas 
// busque la posición (primer nombre, segundo nombre...) del vector en la que se almacenó
// el nombre de una persona que el usuario ingresa y comuniquelo. 
// Si dicho nombre no está en el vector, el programa deberá informarlo. 
// Separe los nombres del vector con comas.

int main()
{
  char nombres[] = "david,juan,maria,berta";
  char nombre_usuario[10];
  
  printf("Introduzca un nombre para buscar en mi cadena: ");
  scanf("%9s", nombre_usuario); 
  
  int i=0, j=0;
  // usamos esta variable para contar cuantas lestras han sido iguales
  int iguales = 0;
  // debemos llevar cuenta de la posición de nombre que estamos 
  // inicializamos en 1 porque es la primea posicion
  int posicion = 1;
  // recorre las cadenas hasta que una de ellas llegue al final
  // Y si NO hemos encontrado el nombre
  while( (nombres[i] != '\0') && (nombre_usuario[iguales] != '\0') )
  {
    // comparamos las posiciones 1 a 1
    if(nombres[i] != nombre_usuario[j])
    {
       iguales = 0;
       // Tengo que ir hasta la siguiente coma
       //"david,juan,maria,berta";
       while(nombres[i] != ',')
       {
           i++;
       }  
       // al ir al siguiente nombre, actualizamos el valor de posición
         posicion++;
         // Para que al hacer el j++ de la linea 48, empecemos la siguiente búsqueda en 0
        j=-1;     
    }
    else
    {
      iguales++;
    }

    i++;  
    j++;
  }  
  if(nombre_usuario[iguales] == '\0')
  {
    printf("Si lo he encontrado en la posicion %i.", posicion);
  }
  else
  {
    printf("No lo he encontrado");
  }
  
  return 0;
}

#+END_SRC


* 12. Palabras al revés

Escribe un programa que imprima al revés una frase introducida por teclado. Las letras de cada palabra estarán en orden correcto, pero las palabras deben quedar en orden contrario (ejemplo: \texttt{Escuela de Ingenieros} se convierte en (\texttt{Ingenieros de Escuela}).

#+BEGIN_SRC C 
#include <stdio.h>

int main ()
{
  char frase[31];
  int len, i;
  // Pide la frase al usuario
  printf("Escribe una frase (máximo 30 letras):\n");
  gets(frase);
  
  // Calcula la longitud de la cadena
  i = 0;
  while (frase[i] != '\0')
  {
    i++;
  }
  len = i;
  
  // Usamos estas variables para marcar el inicio y fin de una frase
  int fin = len-1;
  int inicio;
  // Empezamos por el último caracter (len - 1) y retrocedemos hasta
  // el primero (0)
  for(i = len-1; i >= 0; i--)
  {
    // En cada espacio hay una nueva palabra. 
    // Asumimos que no hay puntos ni comas (esto podría mejorarse)
    if(( frase[i] == ' ') || (i==0) )
    {
      if ( frase[i] == ' ')
      {
        inicio = i+1;
      }
      else
      {
        inicio = i;  
      }
      // Imprimimos hasta el final de la palabra
      while(inicio <= fin)
      {
        printf("%c", frase[inicio]);
        inicio++;
      }
      // Asignamos el nuevo fin
      fin = i-1;
      printf(" ");
    }
    
  }
    
  return 0;
}
#+END_SRC

#+END_SRC





