#+TITLE: Ejercicios del Tema 6
#+SUBTITLE: Ficheros
#+AUTHOR: 
#+DATE: 
#+SETUPFILE: config.org
#+PROPERTY: header-args :exports none
#+EXPORT_FILE_NAME: ejercicios_tema7.pdf

* Cambio de espacios por guión bajo
Escribe un programa que, dada una frase introducida por el usuario, cambie los espacios en blanco por un guión bajo _. Debe contar cuántos cambios se han producido. La petición de la frase debe programarse en la función main, los cambios y la cuenta en la función espacio_por_guion, y la frase definitiva y el número de cambios deben mostrarse en el terminal desde la función main. El ejercicio debe resolverse empleando una función con el siguiente prototipo:
#+BEGIN_SRC C :exports code
int espacio_por_guion(char texto[]);
#+END_SRC

#+BEGIN_SRC C
#define MAX 100

// Función que reemplaza espacios por guiones bajos y devuelve el número de cambios
int espacio_por_guion(char texto[]);

int main() 
{
    char frase[MAX];

    printf("Introduce una frase: ");
    scanf("%[^\n]s", frase);

    int total_cambios = espacio_por_guion(frase);

    printf("\nFrase modificada: %s", frase);
    printf("Numero de cambios realizados: %d\n", total_cambios);

    return 0;
}

int espacio_por_guion(char texto[])
{
  int num_cambio=0;
  int i = 0;
  while (texto[i] != '\0')
  {
    if (texto[i] == ' ')
    {
      texto[i] = '_'; // Cambiamos espacios por guiones
      num_cambio++;
    } 
    i++;
  }
  return num_cambio;
}
#+END_SRC

#+RESULTS:

* Cuenta letras

Escribe un programa que analice una frase introducida por el usuario contando en número de veces que aparece cada vocal, de manera similar al ejercicio del tema 4 de cadenas de caracteres. Al final del programa, se debe pintar en el terminal, para cada vocal, una línea que contiene el mismo número de asteríscos que veces aparece esa vocal. Este programa debe estar programado empleando dos funciones, cuentaLetra y pintaAsteriscos. Puedes usar el fichero lorem_ipsum.txt como ejemplo. 

#+BEGIN_SRC C
#include <stdio.h>

int cuentaLetra(char x, char texto[]);
void pintaAsteriscos(int n);

int main()
{
  FILE *pf;
  char texto[1000];
  char vocales[5] = {'a', 'e', 'i', 'o', 'u'};
  int i = 0; 
  // Creamos un vector de contadores de vocales
  int num_Vocales[5] = {0};
  // Leemos el testo incluyendo espacios
  scanf("%[^\n]s", texto);

  // Recorremos texto contando vocales
  for (i = 0; i < 5; i++)
  {
    // En cada llamada, pasamos a la función como argumento un contador distinto
    num_Vocales[i] = cuentaLetra(vocales[i], texto);
  }
  
  for (i = 0; i < 5; i++)
  { 
    // Recorre el vector de resultados, y pinta asteriscos
    // correspondientes a cada letra
    printf("%c: ", vocales[i]);
    pintaAsteriscos(nVocales[i]);
    printf("\n");
  }
  fclose(pf);
  
  return 0;
}

int cuentaLetra(char x, char texto[])
{
  int i, n = 0;
  int inc = 'A' - 'a';

  i = 0;

  while (texto[i] != '\0')
  {
    // Comprueba mayúsculas y minúsculas
    if (texto[i] == x || texto[i] == x + inc)
    {
      n++; // Contador de apariciones
    }
    i++;
  }

  return n;
}

void pintaAsteriscos(int n)
{
  int i;
  if (n > 0)
  {
    for (i = 1; i <= n; i++)
    {
      printf("*");
    }  
  }    
}
#+END_SRC

#+RESULTS:
| Caracteres: 848 | Palabras: 146 | Líneas: 16. |


* Audio
Las muestras obtenidas de la digitalización de una señal de audio (con un micrófono) están definidas
por: una cadena de caracteres que representa el nombre de la señal, un número entero que es el número
de muestras, y el resto de filas son los números reales que representan las muestras léidas por el sensor. Elabore un programa que:

- Use la estructura indicada más adelante para guardar una señal.

- Declare una variable de ese tipo de estructura e inicialice sus valores con 10 muestas. La inicialización se hace en el código, no la hace el usuario.

Definición de la estructura:
#+BEGIN_SRC C
typedef struct
{
  char nombre[50]; // Nombre de la señal
  int n_muestras; // Número de muestras
  float muestras[100]; // Muestras
}audio;
#+END_SRC C

Finalmente, implemente una función que calcule y devuelva la mediana de ese vector.

Finalmente, implemente una función que calcule y devuelva la mediana de ese vector.

#+BEGIN_SRC C
#include <stdio.h>

// Definición de la estructura
typedef struct {
    char nombre[50];     // Nombre de la señal
    int n_muestras;      // Número de muestras
    float muestras[100]; // Muestras
} audio;

float calcular_mediana(float datos[], int n);

int main() 
{
    // Inicialización de la variable de tipo audio
    audio mi_audio = {
        "voz_lectura",
        10,
        {0.25, 0.30, 0.15, 0.45, 0.50, 0.60, 0.35, 0.40, 0.20, 0.55}
    };

    // Copiar las muestras para no modificar el original al ordenar
    float copia[100];
    for (int i = 0; i < mi_audio.n_muestras; i++) 
    {
        copia[i] = mi_audio.muestras[i];
    }

    float mediana = calcular_mediana(copia, mi_audio.n_muestras);

    // Mostrar resultado
    printf("Nombre de la señal: %s\n", mi_audio.nombre);
    printf("Número de muestras: %i\n", mi_audio.n_muestras);
    printf("Mediana de las muestras: %.2f\n", mediana);

    return 0;
}

// Función para calcular la mediana
float calcular_mediana(float datos[], int n)
{
    int i, j;
    float temp;

    // Primero, ordenamos los datos del vector
    for (i = 0; i < n - 1; i++) 
    {
        for (j = 0; j < n - i - 1; j++) 
        {
            if (datos[j] > datos[j + 1]) 
            {
                temp = datos[j];
                datos[j] = datos[j + 1];
                datos[j + 1] = temp;
            }
        }
    }

    // Calcular mediana, buscamos el dato del medio
    // Si tenemos un numero par de datos, devolvemos la media de los 2 de en medio
    float resultado;
    if (n % 2 == 0) 
    {
        resultado = datos[n / 2 - 1] + datos[n / 2]) / 2;
    } else 
    {
        resultado = datos[n / 2];
    }
    return resultado;
}

#+END_SRC C

* Nóminas

Se debe calcular la nómina mensual de un empleado que trabaja por horas, el pago de cada hora trabajada depende de su categoría:
categoría | pago x hora (€.)
| A | 30.00
| B |20.50
| C | 18.50

Además, si el empleado trabaja más de 150 horas mensuales tiene una bonificación del 5% de nómina. El programa que calcula la nómina está compuesto por dos funciones, una que solicita los datos del empleado por teclado y otra función que calcula la nómina mensual. El programa principal debe mostrar la nómina mensual calculada del empleado introducido. Para los datos del empleado se debe usar la siguiente estructura:
#+BEGIN_SRC C
typedef struct
{
  char nom[40], categoria;
  int horas;
  float nomina, pHora, bonf;
} empleado;


Los prototipos de las funciones que se tienen que utilizar son los siguientes: 
#+BEGIN_SRC C

empleado pedirDatos(empleado emp);
float calcularNomina (empleado);
#+END_SRC

Ejemplo de ejecución:
Introduzca nombre empleado: Pepe Campo
Introduzca categoría del empleado: B
Introduzca horas trabajadas: 25
La nómina total del empleado Pepe Campo es: 512.50 euros, con un total de 0 euros de bonificación
extra.
#+BEGIN_SRC C
#include <stdio.h>

typedef struct
{
  char nom[40], categoria;
  int horas;
  float nomina, pHora, bonf;
} empleado;

// Funcion encargada de pedir los datos al usuario
empleado pedirDatos();

// Funcion encargada de calcular la nomina mensual del empleado
float calcularNomina (empleado emp);

int main()
{
  empleado emp;
  
  // se asigna a una variable de tipo empleado
  // el valor devuelto por la función pedirDatos
  emp = pedirDatos();
  
  // se asigna a una variable de tipo float
  // el valor devuelto por la función calcularNomina
  // y se guarda en la variable nómina dentro de la estructura
  emp.nomina = calcularNomina(emp);
  
  // se calcula la bonificación en caso de ser necesario
  if(emp.horas > 150)
  {
    emp.bonf = emp.nomina * 0.05;
  }
  else
  {
    emp.bonf = 0;
  }
  emp.nomina = emp.nomina + emp.bonf;
  
  printf("La nómina total del empleado %s es: %f euros, con un total de %f euros de bonificacion extra.", emp.nom, emp.nomina, emp.bonf);
  return 0;
}

empleado pedirDatos()
{
  empleado persona;
  printf("Introduzca nombre empleado: ");
  scanf("%39[^\n]", persona.nom);
  
  fflush(stdin);
  printf("\nIntroduzca categoría del empleado: ");
  scanf("%c", &persona.categoria);
  
  printf("\nIntroduzca horas trabajadas: ");
  scanf("%i", &persona.horas);
  
  return persona;
}

float calcularNomina (empleado emp)
{  
  // de asigna el precio hora según la categoría
  // podría hacerse son if...else encadenados
  switch(emp.categoria)
  {
    case 'A':
      emp.pHora = 30.0;
      break;
    case 'B':
      emp.pHora = 20.5;
      break;
    case 'C':
      emp.pHora = 18.5;
      break;
    default:
      printf("Esta catergoria no existe\n");  
  }
  
  emp.nomina = emp.pHora*emp.horas;
  

  return emp.nomina;
}
#+END_SRC C


* Texto
Realice un programa en lenguaje C que solicite una frase al usuario, la modifique y presente en
pantalla el resultado, con las siguientes características:

- Tendrá una función, int modificaT(char texto[]), que realizará las siguientes acciones:
#+BEGIN_SRC C
int modificaT(char texto[]) 
#+END_SRC C
    - Solicitar al usuario una letra
    - Solicitar al usuario una frase
    - Localizar la letra en el texto y sustituirla por: el caráter 5 si la letra aparece en mayúsculas, o por el carácter 7 si la letra aparece en minúsculas.
- El retorno de la función será el número de sustituciones realizadas.
- La presentación de la frase modificada se hará desde main e incluirá el número de sustituciones realizadas. Si no hay modificaciones solo aparecerá el correspondiente mensaje.
- Finalmente se preguntará al usuario si desea repetir el proceso con una nueva frase y se procederá en consecuencia.

#+BEGIN_SRC C
#include <stdio.h>
#include <string.h>

#define MAX_FRASE 100

// Prototipo de la función que modifica la frase
int modificaT(char texto[]);

int main() 
{
    char frase[MAX_FRASE];
    int repetir;

    do {
        // Modificar la frase
        int numSustituciones = modificaT(frase);

        // Mostrar la frase modificada y el número de sustituciones
        printf("Frase modificada: %s\n", frase);
        
        if (numSustituciones > 0) 
        {
            printf("Numero de sustituciones realizadas: %i\n", numSustituciones);
        } 
        else 
        {
            printf("No se realizaron sustituciones.\n");
        }

        // Preguntar si desea repetir el proceso
        printf("Desea introducir una nueva frase? Pulse cero para salir. ");
        scanf("%i", &repetir);
    } while (repetir !== 0);

    return 0;
}

// Implementación de la función que modifica la frase
int modificaT(char texto[]) 
{
    char letra;
    int sustituciones = 0;

    // Solicitar la letra al usuario
    printf("Introduce una letra: ");
    scanf("%c", &letra);

    // Solicitar la frase al usuario
    printf("Introduce una frase (max %i caracteres): ", MAX_FRASE - 1);
    scanf("%99[^\n]s", frase);

    // Recorrer el texto y realizar las sustituciones
    int i;
    for (i = 0; texto[i] != '\0'; i++) 
    {
      if (texto[i] == letra) 
      {
        if (letra >= 'A' && letra <= 'Z') 
        {
          texto[i] = '5';
        } 
        else
        {
          if (letra >= 'a' && letra <= 'z') 
          {
            texto[i] = '7';
          }
        }
        sustituciones++;
      }
    }

    return sustituciones;
}
#+END_SRC C



* Almacén
Se desea hacer un programa informático que calcule la cantidad de dinero inmovilizado en un almacén de productos. El dinero inmovilizado equivale al precio por unidad del producto multiplicado por la cantidad de productos disponibles en el almacén. Además, si la cantidad de productos en el almacén es menor o igual a 10 unidades, debe indicar la necesidad de hacer el pedido de dicho producto.
Estructure su código de la siguiente manera.
- Generación del Almacén: vector de estructuras cuya dimensión se establece al inicio del programa según las necesidades del usuario. Formato del tipo de dato:
#+BEGIN_SRC C
typedef struct
{
  char cod[5]; //Código del prodcuto
  int stock; //cantidad de producto en almacen
  float precio; //precio por unidad
}INV;
#+END_SRC C
- Inicialización del Almacén: se realiza mediante la función generaInventario(). Esta función recibe como parámetros el vector de estructuras y la cantidad de elementos del vector. El usuario debe introducir por teclado cada uno de los elementos de la estructura a fin de inicializarla:
#+BEGIN_SRC C
void generaInventario(INV inventario[], int numero_items);
#+END_SRC C
- Gestión del Almacén:: se realiza mediante una función que recibe como argumento un elemento (solo UNO) del vector de estructura previamente inicializado y calcula la cantidad de dinero inmovilizado en el almacén, en euros. Además, avisa al usuario si se necesita hacer un perido cuando el stock sea menor o igual a 10. La función retorna la cantidad de euros inmovilizados del producto:
#+BEGIN_SRC C
float calculaInmovilizado(INV producto)
#+END_SRC C


#+BEGIN_SRC C
#include <stdio.h>
#include <string.h>

#define MAX_CODIGO 5
#define NUM_ITEMS 2

typedef struct 
{
    char cod[MAX_CODIGO]; // Código del producto
    int stock;            // Cantidad de producto en almacén
    float precio;         // Precio por unidad
} INV;

// Prototipos de las funciones
void generaInventario(INV inventario[], int numero_items);
float calculaInmovilizado(INV producto);

int main() 
{
    int numero_items;

    // Crear el vector de estructuras INV
    // con numero de onjetos inventariados fijo 
    INV inventario[NUM_ITEMS];

    // Inicializar el inventario
    generaInventario(inventario, NUM_ITEMS);

    // Calcular y mostrar el dinero inmovilizado en el almacén
    float total_inmovilizado = 0;
    int i;
    for (i = 0; i < NUM_ITEMS; i++) 
    {
        float inmovilizado = calculaInmovilizado(inventario[i]);
        total_inmovilizado = total_inmovilizado + inmovilizado;
    }

    printf("Dinero total inmovilizado en el almacén: %.2f euros\n", total_inmovilizado);

    return 0;
}

// Implementación de la función generaInventario
void generaInventario(INV inventario[], int numero_items) 
{
    int i;
    for (i = 0; i < numero_items; i++) 
    {
        printf("Introduce los datos del producto %i\n", i + 1);
        printf("Código del producto: ");
        scanf("%s", inventario[i].cod);

        printf("Cantidad en almacén: ");
        scanf("%i", &inventario[i].stock);
        printf("Precio por unidad: ");
        scanf("%f", &inventario[i].precio);
    }
}

// Implementación de la función calculaInmovilizado
float calculaInmovilizado(INV producto) 
{
    float inmovilizado = producto.precio * producto.stock;

    if (producto.stock <= 10) 
    {
        printf("El producto con código %s necesita ser pedido. Stock actual: %i\n", producto.cod, producto.stock);
    }

    return inmovilizado;
}

#+END_SRC C





